unit TestuOrderProcessor;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uOrder, uOrderEntry, uOrderValidator, uOrderProcessor;

type
  // Test methods for class TOrderProcessor

  TestTOrderProcessor = class(TTestCase)
  strict private
    FOrderProcessor: TOrderProcessor;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestProcessOrder;
  end;

implementation

procedure TestTOrderProcessor.SetUp;
begin
  FOrderProcessor := TOrderProcessor.Create;
end;

procedure TestTOrderProcessor.TearDown;
begin
  FOrderProcessor.Free;
  FOrderProcessor := nil;
end;

procedure TestTOrderProcessor.TestProcessOrder;
var
  aOrder: TOrder;
begin
  // TODO: Setup method call parameters
  aOrder := TOrder.Create;
  try
    Check(FOrderProcessor.ProcessOrder(aOrder));
  finally
    aOrder.Free;
  end;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTOrderProcessor.Suite);
end.

